- name: Set up SSH for Deployment

  run: |

    mkdir -p ~/.ssh

    echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa

    chmod 600 ~/.ssh/id_rsa

    ssh-keyscan -H 3.108.196.2 >> ~/.ssh/known_hosts
